### ISSUE TITLE
Action that triggers on issue creation

### ISSUE THREAD

**Issue by simonw** [simonw/action-transcription-prototype#2]
Refs:
- #1

Started prototyping that here: https://github.com/simonw/try-out-issue-template-forms/issues/1 - with this issue template (only allowed in public repos at the moment): https://github.com/simonw/try-out-issue-template-forms/blob/afe6c8e3ed86ba03fb7318ce8131613ff4ecf16c/.github/ISSUE_TEMPLATE/url.yml

```yaml
name: URL workflow
description: Process a URL
title: "[URL]: "
labels: ["url"]
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: URL to an article or video
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: What action would you like to take?
      options:
        - Extract transcript from video
        - Extract transcript from video and translate to English
    validations:
      required: true
```

The issue that this creates looks like this:

```
### URL

https://www.youtube.com/watch?v=OJIzTVyxIAw

### What action would you like to take?

Extract transcript from video and translate to English
```
